import { Student, AcademicGrade, FinancialTransaction, AbsenceRecord, DocumentItem, TimelineEvent } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'EST-2024-0145',
    matricula: '20230145',
    nomeCompleto: 'Ana Catarina Mendes Silva',
    nomeSocial: 'Ana Silva',
    dataNascimento: '18 Maio 2008',
    nacionalidade: 'Portuguesa',
    nif: '234 567 890',
    cartaoCidadao: '14523981 4 ZX9',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    classe: '10º Ano',
    turma: 'Turma A',
    curso: 'Ciências Físicas',
    encarregadoNome: 'Manuel Silva',
    encarregadoParentesco: 'Pai',
    encarregadoTelefone: '923 456 789',
    encarregadoEmail: 'manuel.silva@email.com',
    contactoEstudante: '923 456 789',
    emailEstudante: 'ana.silva@student.vendaia.edu',
    estadoMatricula: 'Ativo',
    situacaoFinanceira: 'Regularizada',
    documentacaoPendente: 'ok',
    morada: {
      endereco: 'Av. da Liberdade, nº 102, 2º Dto',
      codigoPostal: '1250-001',
      localidade: 'Lisboa',
      concelhoDistrito: 'Lisboa, Lisboa'
    },
    tutorAcademico: 'Dra. Helena Martins',
    mediaGeral: 16.8,
    creditosECTS: 120,
    taxaAssiduidade: 96,
    dataMatricula: '10 Set 2023'
  },
  {
    id: 'EST-2022-1089',
    matricula: '20221089',
    nomeCompleto: 'Bruno Miguel Santos Costa',
    nomeSocial: 'Bruno Costa',
    dataNascimento: '22 Jan 2007',
    nacionalidade: 'Portuguesa',
    nif: '241 890 123',
    cartaoCidadao: '13982104 2 YX1',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    classe: '11º Ano',
    turma: 'Turma B',
    curso: 'Economia',
    encarregadoNome: 'Maria Costa',
    encarregadoParentesco: 'Mãe',
    encarregadoTelefone: '931 222 333',
    encarregadoEmail: 'maria.costa@email.com',
    contactoEstudante: '931 222 333',
    emailEstudante: 'bruno.costa@student.vendaia.edu',
    estadoMatricula: 'Ativo',
    situacaoFinanceira: 'Pendente',
    documentacaoPendente: 'foto',
    morada: {
      endereco: 'Rua das Amoreiras, Lote 12',
      codigoPostal: '1070-002',
      localidade: 'Lisboa',
      concelhoDistrito: 'Lisboa, Lisboa'
    },
    tutorAcademico: 'Prof. Carlos Silva',
    mediaGeral: 15.2,
    creditosECTS: 110,
    taxaAssiduidade: 91,
    dataMatricula: '12 Set 2022'
  },
  {
    id: 'EST-2023-0512',
    matricula: '20230512',
    nomeCompleto: 'Carlos Eduardo Ferreira',
    nomeSocial: 'Carlos Ferreira',
    dataNascimento: '04 Out 2008',
    nacionalidade: 'Portuguesa',
    nif: '255 123 456',
    cartaoCidadao: '15012399 7 WX3',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    classe: '10º Ano',
    turma: 'Turma C',
    curso: 'Ciências Físicas',
    encarregadoNome: 'António Ferreira',
    encarregadoParentesco: 'Pai',
    encarregadoTelefone: '924 111 222',
    encarregadoEmail: 'antonio.ferreira@email.com',
    contactoEstudante: '924 111 222',
    emailEstudante: 'carlos.ferreira@student.vendaia.edu',
    estadoMatricula: 'Ativo',
    situacaoFinanceira: 'Regularizada',
    documentacaoPendente: 'ok',
    morada: {
      endereco: 'Praca Marquês de Pombal, 5',
      codigoPostal: '1250-160',
      localidade: 'Lisboa',
      concelhoDistrito: 'Lisboa, Lisboa'
    },
    tutorAcademico: 'Dr. António Costa',
    mediaGeral: 17.5,
    creditosECTS: 120,
    taxaAssiduidade: 98,
    dataMatricula: '11 Set 2023'
  },
  {
    id: 'EST-2023-0891',
    matricula: '20230891',
    nomeCompleto: 'Daniela Sofia Santos',
    nomeSocial: 'Daniela Santos',
    dataNascimento: '14 Nov 2006',
    nacionalidade: 'Portuguesa',
    nif: '260 987 654',
    cartaoCidadao: '14902381 0 AX2',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    classe: '12º Ano',
    turma: 'Turma A',
    curso: 'Artes Visuais',
    encarregadoNome: 'Isabel Santos',
    encarregadoParentesco: 'Mãe',
    encarregadoTelefone: '945 333 444',
    encarregadoEmail: 'isabel.santos@email.com',
    contactoEstudante: '945 333 444',
    emailEstudante: 'daniela.santos@student.vendaia.edu',
    estadoMatricula: 'Ativo',
    situacaoFinanceira: 'Regularizada',
    documentacaoPendente: 'cert',
    morada: {
      endereco: 'Rua Garrett, nº 44, 3º C',
      codigoPostal: '1200-204',
      localidade: 'Lisboa',
      concelhoDistrito: 'Lisboa, Lisboa'
    },
    tutorAcademico: 'Prof. Teresa Mendes',
    mediaGeral: 18.1,
    creditosECTS: 180,
    taxaAssiduidade: 95,
    dataMatricula: '09 Set 2021'
  },
  {
    id: 'EST-2022-0045',
    matricula: '20220045',
    nomeCompleto: 'Eduardo Jorge Lima',
    nomeSocial: 'Eduardo Lima',
    dataNascimento: '30 Mar 2007',
    nacionalidade: 'Portuguesa',
    nif: '211 456 789',
    cartaoCidadao: '13129840 9 BX4',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    classe: '11º Ano',
    turma: 'Turma B',
    curso: 'Economia',
    encarregadoNome: 'Jorge Lima',
    encarregadoParentesco: 'Pai',
    encarregadoTelefone: '912 555 666',
    encarregadoEmail: 'jorge.lima@email.com',
    contactoEstudante: '912 555 666',
    emailEstudante: 'eduardo.lima@student.vendaia.edu',
    estadoMatricula: 'Inativo',
    situacaoFinanceira: 'Dívida',
    documentacaoPendente: 'bi',
    morada: {
      endereco: 'Rua Augusta, 120',
      codigoPostal: '1100-053',
      localidade: 'Lisboa',
      concelhoDistrito: 'Lisboa, Lisboa'
    },
    tutorAcademico: 'Mr. David Smith',
    mediaGeral: 11.4,
    creditosECTS: 80,
    taxaAssiduidade: 78,
    dataMatricula: '15 Set 2022'
  },
  {
    id: 'EST-2024-089',
    matricula: '20230892',
    nomeCompleto: 'João Miguel Santos Almeida',
    nomeSocial: 'João Almeida',
    dataNascimento: '15 Abril 2008',
    nacionalidade: 'Portuguesa',
    nif: '245 879 102',
    cartaoCidadao: '14829472 8 ZX3',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB01l7UEN3mN2aHFX_CNbxJwZhYQd3OB6BCblx643CdWHBKCV-Mq6lD1UqBaaYvEuw_cGhgrU37_1nWgoFQ9mC-eCnYvvKjrDfEo9BICqbeAv0JMFNEOEbq7fxmDEBSz_fAOsr0WKqtJjWxGiykOfcluJAh_XAIeFz5SVkRDc6W0XnTrAZrIpMlJiBbayb0atVjMwXwD6A_UCGrW202zIAYZPIiDRUe4W_S_aZGWxP-J3wQN4ldGwsMeg',
    classe: '10º Ano',
    turma: 'Turma A',
    curso: 'Ciências e Tecnologias',
    encarregadoNome: 'Maria de Fátima Santos Almeida',
    encarregadoParentesco: 'Mãe',
    encarregadoTelefone: '+351 965 432 198',
    encarregadoEmail: 'mf.almeida@email.com',
    contactoEstudante: '+351 912 345 678',
    emailEstudante: 'joao.almeida@vendaia.pt',
    estadoMatricula: 'Ativo',
    situacaoFinanceira: 'Regularizada',
    documentacaoPendente: 'ok',
    morada: {
      endereco: 'Rua das Flores, Lote 4, 3º Esq.',
      codigoPostal: '1200-098',
      localidade: 'Lisboa',
      concelhoDistrito: 'Lisboa, Lisboa'
    },
    tutorAcademico: 'Dr. Carlos Mendes',
    mediaGeral: 17.2,
    creditosECTS: 120,
    taxaAssiduidade: 94,
    dataMatricula: '12 Set 2021'
  },
  {
    id: 'STU-2023-8942',
    matricula: '20230893',
    nomeCompleto: 'Maria Joana Silva Santos',
    nomeSocial: 'Maria Santos',
    dataNascimento: '12 Set 2005',
    nacionalidade: 'Portuguesa',
    nif: '254 998 123',
    cartaoCidadao: '14102938 3 CX5',
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDl5yIhGXx1uYBf-ILyTHHuFmVXqEgcOKaLT25-yHNRn_2cKZ7uX85gWvqOGnltv6S26asB-BteduECS0_DTECGPJC1nRgUN9U3XUYBIfSEoyfWWY9ttwB50Y-5qoFZeSk-qiOOeKOjKnCGIJhkcA8DabokMDX24DXEvWk5woVMQRJGXnlSCkPYPrC5xyPenn-hWnk665xc0SWZBz22GdKqioZB9fn6VHVyR2GA-aTGIwXVjbhqeKufYw',
    classe: '12º Ano',
    turma: 'Turma B',
    curso: 'Engenharia Informática',
    encarregadoNome: 'Dr. Roberto Santos',
    encarregadoParentesco: 'Pai',
    encarregadoTelefone: '+351 912 345 678',
    encarregadoEmail: 'roberto.santos@email.com',
    contactoEstudante: '+351 912 345 678',
    emailEstudante: 'm.santos@student.vendaia.edu',
    estadoMatricula: 'Ativo',
    situacaoFinanceira: 'Regularizada',
    documentacaoPendente: 'ok',
    morada: {
      endereco: 'Av. Almirante Reis, nº 88',
      codigoPostal: '1150-020',
      localidade: 'Lisboa',
      concelhoDistrito: 'Lisboa, Lisboa'
    },
    tutorAcademico: 'Dr. Carlos Mendes',
    mediaGeral: 16.4,
    creditosECTS: 120,
    taxaAssiduidade: 94,
    dataMatricula: '12 Set 2021'
  }
];

export const INITIAL_GRADES: AcademicGrade[] = [
  { id: '1', disciplina: 'Matemática A', iconName: 'calculate', professor: 'Dra. Helena Martins', nota1Per: 15, notaFinal: 16, estado: 'Aprovado' },
  { id: '2', disciplina: 'Português', iconName: 'menu_book', professor: 'Prof. Carlos Silva', nota1Per: 14, notaFinal: 15, estado: 'Aprovado' },
  { id: '3', disciplina: 'Física e Química A', iconName: 'science', professor: 'Dr. António Costa', nota1Per: 17, notaFinal: 18, estado: 'Aprovado' },
  { id: '4', disciplina: 'Geografia A', iconName: 'public', professor: 'Prof. Teresa Mendes', nota1Per: 12, notaFinal: 13, estado: 'Aprovado' },
  { id: '5', disciplina: 'Inglês', iconName: 'language', professor: 'Mr. David Smith', nota1Per: 9, notaFinal: 10, estado: 'Aprov. Condicional' },
];

export const INITIAL_FINANCIALS: FinancialTransaction[] = [
  { id: 'f1', descricao: 'Mensalidade - Setembro 2023', dataVencimento: '10 Set 2023', valor: 450.00, estado: 'Pago', dataPagamento: '08 Set 2023' },
  { id: 'f2', descricao: 'Seguro Escolar Anual', dataVencimento: '01 Set 2023', valor: 85.00, estado: 'Pago', dataPagamento: '01 Set 2023' },
  { id: 'f3', descricao: 'Mensalidade - Outubro 2023', dataVencimento: '10 Out 2023', valor: 450.00, estado: 'Emitido' },
];

export const INITIAL_ABSENCES: AbsenceRecord[] = [
  { id: 'a1', data: '15 Out 2023', disciplina: 'Engenharia de Software II', tipo: 'Teórica', estado: 'Justificada', observacao: 'Atestado médico entregue' },
  { id: 'a2', data: '12 Out 2023', disciplina: 'Sistemas Operativos', tipo: 'Prática', estado: 'Não Justificada', observacao: 'Pendente de justificação' },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  { id: 'd1', tipo: 'Cartão de Cidadão', iconName: 'badge', dataUpload: '12 Set 2021', validade: '30 Dez 2025', estado: 'VALIDADO' },
  { id: 'd2', tipo: 'Certificado de Habilitações', iconName: 'school', dataUpload: '12 Set 2021', validade: 'N/A', estado: 'VALIDADO' },
  { id: 'd3', tipo: 'Boletim de Vacinas', iconName: 'vaccines', dataUpload: '05 Out 2023', validade: '10 Nov 2023', estado: 'PENDENTE' },
  { id: 'd4', tipo: 'Fotografia', iconName: 'portrait', dataUpload: '12 Set 2021', validade: '12 Set 2023', estado: 'EXPIRADO' },
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 't1',
    studentId: 'EST-2024-089',
    timestamp: '10:45',
    dateCategory: 'Hoje',
    categoria: 'finance',
    categoriaLabel: 'Financeiro',
    badgeBg: 'bg-green-100',
    badgeText: 'text-green-800',
    icon: 'payments',
    iconColor: 'text-success',
    titulo: 'Fatura Liquidada',
    descricao: 'Liquidação da propina referente a Outubro 2024. Fatura Recibo FT 2024/1042 gerada com sucesso via Referência Multibanco.',
    autorName: 'Sistema Automático',
    autorType: 'system',
    actionText: 'Ver Fatura'
  },
  {
    id: 't2',
    studentId: 'EST-2024-089',
    timestamp: '09:15',
    dateCategory: 'Hoje',
    categoria: 'academic',
    categoriaLabel: 'Académico',
    badgeBg: 'bg-blue-100',
    badgeText: 'text-blue-800',
    icon: 'book',
    iconColor: 'text-info',
    titulo: 'Nota Lançada',
    descricao: 'Avaliação Intercalar de Matemática A inserida. Classificação: 16 Valores.',
    autorName: 'Prof. Rui Martins',
    autorType: 'professor',
    autorPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80'
  },
  {
    id: 't3',
    studentId: 'EST-2024-089',
    timestamp: '16:30',
    dateCategory: 'Ontem',
    categoria: 'documental',
    categoriaLabel: 'Documental',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-800',
    icon: 'description',
    iconColor: 'text-amber-500',
    titulo: 'Documento Pendente',
    descricao: 'Notificação enviada ao encarregado de educação solicitando a atualização do Cartão de Cidadão (caducado em 10/10/2024).',
    autorName: 'Secretaria - Sara Silva',
    autorType: 'secretary'
  },
  {
    id: 't4',
    studentId: 'EST-2024-089',
    timestamp: '09:00',
    dateCategory: '12 Set',
    categoria: 'administrative',
    categoriaLabel: 'Administrativo',
    badgeBg: 'bg-surface-container-high',
    badgeText: 'text-on-surface-variant',
    icon: 'how_to_reg',
    iconColor: 'text-outline',
    titulo: 'Matrícula Renovada',
    descricao: 'Matrícula confirmada para o 10º Ano, Turma A. Processo concluído com sucesso e turmas alocadas.',
    autorName: 'Admin Direção',
    autorType: 'admin',
    autorPhoto: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80'
  }
];
